Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/05/2023
Var
// Seção de Declarações das variáveis 
x: caractere
y: inteiro
z: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para y:=1 até z faca
x <- x+"*";
z <- z+1;
escreva x
fimpara
Fimalgoritmo